### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by CrazyCoder** [ufian/soap4me-repo#1]
При попытке открыть 2 сезон сериала Mr. Robot появляется ошибка и список серий не выводится. Версия плагина последняя (1.0.7), удаление кэша не помогает.

```
05:56:20 T:140053472847616   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/home/user/.kodi/addons/plugin.video.soap4.me/addon.py", line 1166, in <module>
                                                addon_main()
                                              File "/home/user/.kodi/addons/plugin.video.soap4.me/addon.py", line 1136, in addon_main
                                                rows = api.process(parts)
                                              File "/home/user/.kodi/addons/plugin.video.soap4.me/addon.py", line 1035, in process
                                                rows = all_episodes.list_episodes(int(parts.season), self.config)
                                              File "/home/user/.kodi/addons/plugin.video.soap4.me/addon.py", line 824, in list_episodes
                                                rows.extend(self.episodes[season][episode_num].menu(config))
                                              File "/home/user/.kodi/addons/plugin.video.soap4.me/addon.py", line 753, in menu
                                                files = config.filter_files(self.data['files'])
                                              File "/home/user/.kodi/addons/plugin.video.soap4.me/addon.py", line 516, in filter_files
                                                translates = self._choice_translate(files)
                                              File "/home/user/.kodi/addons/plugin.video.soap4.me/addon.py", line 494, in _choice_translate
                                                translates = set([to_int(f['translate']) for f in files])
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
05:56:20 T:140055834474496   ERROR: GetDirectory - Error getting plugin://plugin.video.soap4.me/?page=Episodes&param=my&season=2&sid=509
05:56:20 T:140055834474496   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.soap4.me/?page=Episodes&param=my&season=2&sid=509) failed
05:56:20 T:140053472847616  NOTICE: ['plugin://plugin.video.soap4.me/', '49', '?page=Episodes&param=my&sid=509']
05:56:21 T:140053909071616  NOTICE: ['plugin://plugin.video.soap4.me/', '50', '?page=My&param=my']
05:56:22 T:140053472847616  NOTICE: ['plugin://plugin.video.soap4.me/', '51', '']
```

**Comment by ufian** [comment]
У меня открывается. Судя по ошибке - неправильно API отдавал.

**Comment by CrazyCoder** [comment]
Да, само починилось через день.
