### ISSUE TITLE
HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by tarapon** [ufian/soap4me-repo#3]
Plugin crash after setting username and password.
Kodi 17 beta, ATV4
Log is:
```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 400: Bad Request
                                            Traceback (most recent call last):
                                              File "/var/mobile/Containers/Data/Application/5B08B8E8-20E4-4DB3-9072-7F04A8577A56/Library/Caches/home/addons/plugin.video.soap4.me/addon.py", line 1326, in <module>
                                                addon_main()
                                              File "/var/mobile/Containers/Data/Application/5B08B8E8-20E4-4DB3-9072-7F04A8577A56/Library/Caches/home/addons/plugin.video.soap4.me/addon.py", line 1250, in addon_main
                                                api = SoapApi()
                                              File "/var/mobile/Containers/Data/Application/5B08B8E8-20E4-4DB3-9072-7F04A8577A56/Library/Caches/home/addons/plugin.video.soap4.me/addon.py", line 961, in __init__
                                                self.auth.auth()
                                              File "/var/mobile/Containers/Data/Application/5B08B8E8-20E4-4DB3-9072-7F04A8577A56/Library/Caches/home/addons/plugin.video.soap4.me/addon.py", line 608, in auth
                                                if not self.login():
                                              File "/var/mobile/Containers/Data/Application/5B08B8E8-20E4-4DB3-9072-7F04A8577A56/Library/Caches/home/addons/plugin.video.soap4.me/addon.py", line 573, in login
                                                data = self.client.request(self.AUTH_URL, KodiConfig.kodi_get_auth())
                                              File "/var/mobile/Containers/Data/Application/5B08B8E8-20E4-4DB3-9072-7F04A8577A56/Library/Caches/home/addons/plugin.video.soap4.me/addon.py", line 418, in request
                                                text = self._request(url, params)
                                              File "/var/mobile/Containers/Data/Application/5B08B8E8-20E4-4DB3-9072-7F04A8577A56/Library/Caches/home/addons/plugin.video.soap4.me/addon.py", line 397, in _request
                                                response = urllib2.urlopen(req, post_data)
                                              File "/Users/Shared/jenkins/workspace/TVOS/tools/depends/xbmc-depends/appletvos9.1_arm64-target/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/Users/Shared/jenkins/workspace/TVOS/tools/depends/xbmc-depends/appletvos9.1_arm64-target/lib/python2.7/urllib2.py", line 435, in open
                                              File "/Users/Shared/jenkins/workspace/TVOS/tools/depends/xbmc-depends/appletvos9.1_arm64-target/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/Users/Shared/jenkins/workspace/TVOS/tools/depends/xbmc-depends/appletvos9.1_arm64-target/lib/python2.7/urllib2.py", line 473, in error
                                              File "/Users/Shared/jenkins/workspace/TVOS/tools/depends/xbmc-depends/appletvos9.1_arm64-target/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/Users/Shared/jenkins/workspace/TVOS/tools/depends/xbmc-depends/appletvos9.1_arm64-target/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 400: Bad Request
                                            -->End of Python script error report<--
```

**Comment by darkwebdev** [comment]
@ufian How do you think, should this issue be closed or moved to the actual [Addon issues](https://github.com/Soap4me/Kodi/issues/)?

**Comment by mbravorus** [comment]
I have the exact same problem (only the paths are different in log) w/ Kodi 17.6 on mi box 3, plugin v1.0.19 installed from repository, login/password correct, tried reinstalling plugin, restarting Kodi (w/clearing cache, w/clearing all app data), rebooting the box - doesn't help, still errors out. Please advise.

**Comment by mbravorus** [comment]
Update: if you encounter this problem, please check that you are entering username and not email for auth - that solved it for me.

**Comment by darkwebdev** [comment]
@ufian if that's reproducible I would suggest to move this issue to [Kodi issues](https://github.com/Soap4me/Kodi/issues/) and fix the problem, it shouldn't crash on incorrect symbols or whatever...

**Comment by mbravorus** [comment]
it crashes on incorrect auth - because server returns 400 instead of 403 or something

**Comment by ufian** [comment]
It's addon problem. Please move issue to that place.
