### ISSUE TITLE
Play action fails after power loss

### ISSUE THREAD

**Issue by synchrone** [ufian/soap4me-repo#5]
```
19:23:04.319 T:546358423776   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.ValueError'>
Error Contents: could not convert string to float: 
Traceback (most recent call last):
  File "/storage/.kodi/addons/plugin.video.soap4.me/addon.py", line 1326, in <module>
    addon_main()
  File "/storage/.kodi/addons/plugin.video.soap4.me/addon.py", line 1258, in addon_main
    rows = api.process(parts)
  File "/storage/.kodi/addons/plugin.video.soap4.me/addon.py", line 1164, in process
    if not self.get_play(all_episodes, parts.season, parts.epnum, parts.eid):
  File "/storage/.kodi/addons/plugin.video.soap4.me/addon.py", line 1100, in get_play
    sv.play()
  File "/storage/.kodi/addons/plugin.video.soap4.me/addon.py", line 213, in play
    pos = self.get_pos()
  File "/storage/.kodi/addons/plugin.video.soap4.me/addon.py", line 198, in get_pos
    pos = max(float(pos), float(self.start_from))
ValueError: could not convert string to float: 
-->End of Python script error report<--
```

This happens if the power is cut mid-playback. The episode that was played back is not playable unless the plugin caches are reset.
Should be easy enough to wrap the player position restore login in a try/catch.

**Comment by ufian** [comment]
I hope I fix it in 1.0.17
